apiVersion: apps/v1
kind: Deployment
metadata:
  name: apartment-service
  labels:
    app: apartment-service
spec:
  selector:
    matchLabels:
      app: apartment-service
  template:
    metadata:
      labels:
        app: apartment-service
    spec:
      containers:
      - name: apartment-service
        image: bobcrutchley/apartment-service:latest
        ports:
        - name: http-port
          containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: apartment-service
spec:
  type: NodePort
  ports:
    - port: 3000
  selector:
    app: apartment-service

